name: t2

on:
  workflow_dispatch:


jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
    - run: "echo 'j1'"
  j2:
    runs-on: ubuntu-latest
    steps:
    - run: "echo 'j2'"
  j3:
    runs-on: ubuntu-latest
    steps:
    - run: "exit 1"
  j4:
    runs-on: ubuntu-latest
    needs: [j1, j2, j3]
    steps:
    - run: "exit 0"

