name: "Test"

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  test-job:
    uses: gscho/reusable-workflow-test/.github/workflows/reusable-workflow-test.yml@main
