name: "Deploy Ephemeral"

on:
  issue_comment:
    types: [created]
    
permissions:
  id-token: write
  contents: read
  pull-requests: write

secrets: inherit

jobs:
  deploy-job:
    uses: gscho/reusable-workflow-test/.github/workflows/reusable-workflow-test.yml@main
