name: t2

on:
  workflow_dispatch:


jobs:
  j1:
    runs-on: ubuntu-2404
    steps:
    - run: "echo 'j1'"
  j2:
    runs-on: ubuntu-2404
    steps:
    - run: "echo 'j2'"
  j3:
    runs-on: ubuntu-2404
    steps:
    - run: "exit 1"

