name: "Test"

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
    
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  test-job:
    uses: gscho/reusable-workflow-test/.github/workflows/reusable-workflow-test.yml@main
